FROM python:3.10-slim-bullseye

LABEL maintainer="foo@bar.com"

ARG CHATGPT_ON_WECHAT_VER

# 设置时区为上海
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN echo /etc/apt/sources.list
# RUN sed -i 's/deb.debian.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apt/sources.list
ENV BUILD_PREFIX=/app

ADD requirements.txt ${BUILD_PREFIX}/requirements.txt
ADD requirements-optional.txt ${BUILD_PREFIX}/requirements-optional.txt

RUN apt-get update \
    && apt-get install -y --no-install-recommends bash ffmpeg espeak libavcodec-extra\
    && cd ${BUILD_PREFIX} \
    && /usr/local/bin/python -m pip install --no-cache --upgrade pip \
    && pip install --no-cache -r requirements.txt \
    && pip install --no-cache -r requirements-optional.txt \
    && pip install azure-cognitiveservices-speech

ADD . ${BUILD_PREFIX}
RUN cd ${BUILD_PREFIX} \
    && cp config-template.json config.json

WORKDIR ${BUILD_PREFIX}

ADD docker/entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh \
    && mkdir -p /home/noroot \
    && mkdir -p ${BUILD_PREFIX}/logs \
    && groupadd -r noroot \
    && useradd -r -g noroot -s /bin/bash -d /home/noroot noroot \
    && chown -R noroot:noroot /home/noroot ${BUILD_PREFIX} /usr/local/lib ${BUILD_PREFIX}/logs

USER noroot

ENTRYPOINT ["/entrypoint.sh"]
